confirmed: '2026-08-25T17:39:09'
n_traded: 23
traded:
- US500
- NAS100
- GER40
- JPN225
- HK50
- UK100
- US2YR
- US5YR
- US10YR
- US30YR
- BUND
- XAU
- XAG
- COPPER
- SpotCrude
- Gasoline
- Coffee
- Cocoa
- Sugar
- Corn
- Cotton
- Soybeans
- Wheat
