confirmed: '2026-08-27T20:16:04'
n_traded: 17
traded:
- US500
- GER40
- JPN225
- HK50
- US10YR
- BUND
- XAU
- COPPER
- SpotCrude
- Gasoline
- Coffee
- Cocoa
- Sugar
- Corn
- Cotton
- Soybeans
- Wheat
